### ISSUE TITLE
Debian Jessie apt-get update fails since Debian packages have been moved

### ISSUE THREAD

**Issue by danielmai** [jepsen-io/jepsen#348]
https://twitter.com/debian/status/1109080168318926851
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

Debian as archived Jessie packages, so I'm not able to run Jepsen tests via the Docker setup anymore.

I'm trying to run Jepsen tests with the Docker setup using the `tutum/debian:jessie` image (the default):
 
```
./up.sh --dev
```

Tests no longer start since Debian has archived the Jessie packages. E.g., I try to run this test:

```
lein run test --local-binary ./dgraph --force-download --upsert-schema --workload bank --nemesis none --time-limit 300
```

And I get this Jepsen error with `apt-get update`:

```
Caused by: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; apt-get update\"", :exit 100, :out "Hit http://security.debian.org jessie/updates InRelease\nIgn http://httpredir.debian.org jessie InRelease\nIgn http://httpredir.debian.org jessie-updates InRelease\nHit http://httpredir.debian.org jessie Release.gpg\nIgn http://httpredir.debian.org jessie-updates Release.gpg\nHit http://httpredir.debian.org jessie Release\nIgn http://httpredir.debian.org jessie-updates Release\nErr http://httpredir.debian.org jessie-updates/main amd64 Packages\n  \nErr http://httpredir.debian.org jessie-updates/main amd64 Packages\n  \nErr http://httpredir.debian.org jessie-updates/main amd64 Packages\n  \nErr http://httpredir.debian.org jessie-updates/main amd64 Packages\n  \nErr http://httpredir.debian.org jessie-updates/main amd64 Packages\n  404  Not Found\nGet:1 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]\nGet:2 http://httpredir.debian.org jessie/main amd64 Packages [9098 kB]\nFetched 9920 kB in 6s (1441 kB/s)\n", :err "W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found\n\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; apt-get update\"", :in "root\n"}}
	at slingshot.support$stack_trace.invoke(support.clj:201) ~[knossos-0.3.4.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:127) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:122) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.invokeStatic(control.clj:163) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.doInvoke(control.clj:160) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invoke(core.clj:652) ~[clojure-1.9.0.jar:na]
	at jepsen.control$exec.invokeStatic(control.clj:179) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec.doInvoke(control.clj:173) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.9.0.jar:na]
	at jepsen.os.debian$update_BANG_.invokeStatic(debian.clj:36) ~[na:na]
	at jepsen.os.debian$update_BANG_.invoke(debian.clj:33) ~[na:na]
	at jepsen.os.debian$maybe_update_BANG_.invokeStatic(debian.clj:42) ~[na:na]
	at jepsen.os.debian$maybe_update_BANG_.invoke(debian.clj:38) ~[na:na]
	at jepsen.os.debian.Debian.setup_BANG_(debian.clj:145) ~[na:na]
	at jepsen.os$fn__2294$G__2288__2298.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at jepsen.os$fn__2294$G__2287__2303.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at clojure.core$partial$fn__5561.invoke(core.clj:2617) ~[clojure-1.9.0.jar:na]
	at jepsen.control$on_nodes$fn__2893.invoke(control.clj:384) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:661) ~[clojure-1.9.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.9.0.jar:na]
	at jepsen.util$real_pmap$launcher__2044$fn__2045.invoke(util.clj:50) ~[jepsen-0.1.12.jar:na]
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.9.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
```

And when I run `apt-get update` from a node directly, I get errors saying the debian repos aren't available:
```
$ docker exec -it jepsen-n1 bash     
root@n1:/# sudo apt-get update
Hit http://security.debian.org jessie/updates InRelease
Ign http://httpredir.debian.org jessie InRelease              
Ign http://httpredir.debian.org jessie-updates InRelease      
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
Hit http://httpredir.debian.org jessie Release.gpg     
Ign http://httpredir.debian.org jessie-updates Release.gpg          
Hit http://httpredir.debian.org jessie Release                      
Ign http://httpredir.debian.org jessie-updates Release
Get:2 http://httpredir.debian.org jessie/main amd64 Packages [9098 kB]
Err http://httpredir.debian.org jessie-updates/main amd64 Packages
  
Err http://httpredir.debian.org jessie-updates/main amd64 Packages
  
Err http://httpredir.debian.org jessie-updates/main amd64 Packages
  
Err http://httpredir.debian.org jessie-updates/main amd64 Packages                                                                                                                          
  
Err http://httpredir.debian.org jessie-updates/main amd64 Packages                                                                                                                          
  404  Not Found
Fetched 9920 kB in 6s (1483 kB/s)                                                                                                                                                           
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I also tried `./up.sh --dev --ubuntu`, which I thought would work since I figured it'd use Ubuntu instead of Debian, but I get the same Debian errors in the worker nodes. It seems like `--ubuntu` still created Debian-based containers instead of Ubuntu-based ones.

**Comment by jacobmbr** [comment]
As a workaround: Patching `jepsen.os.debian` by inserting these two lines [here](https://github.com/jepsen-io/jepsen/blob/master/jepsen/src/jepsen/os/debian.clj#L144) worked for me.

```
(meh (c/exec :rm "/etc/apt/sources.list.d/backports.list"))
(c/exec :sed :-i "'/jessie-updates/d'" "/etc/apt/sources.list")
```

**Comment by jacobmbr** [comment]
As a workaround, adding this line at the top of `docker/node/Dockerfile` fixes it:

```
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list
```

**Comment by jacobmbr** [comment]
I've added an upgraded Dockerfile in #349.

**Comment by mkcp** [comment]
The docker setup is now running on stretch, so this should be fixed

**Comment by danielmai** [comment]
Thanks all for fixing this.

I'm still seeing issues with installing libzip2 during setup. libzip4 is already installed but the test runs still try to install libzip2.

```
root@control:/jepsen/dgraph# lein run test --local-binary ./dgraph --force-download --upsert-schema --rebalance-interval 10h --workload bank --nemesis-interval 30 --nemesis none --time-limit 300 --concurrency 4n
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
22:06:15.947 [main] INFO  jepsen.cli - Test options:
 {:final-recovery-time 10,
 :concurrency 20,
 :skew :small,
 :nemesis-interval 10,
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil},
 :retry-db-setup false,
 :local-binary "./dgraph",
 :defer-db-teardown false,
 :nemesis {:interval 30},
 :nodes ["n1" "n2" "n3" "n4" "n5"],
 :test-count 1,
 :replicas 3,
 :force-download true,
 :time-limit 300,
 :version "1.0.3",
 :upsert-schema true,
 :workload :bank,
 :rebalance-interval "10h"}

INFO [2019-03-27 22:06:16,664] jepsen test runner - jepsen.core Running test:
 {:final-recovery-time 10,
 :concurrency 20,
 :db
 #object[jepsen.dgraph.support$db$reify__3595 0x6cb43fd3 "jepsen.dgraph.support$db$reify__3595@6cb43fd3"],
 :name "dgraph v1.0.12-rc3-247-gf9ba33bd7 bank upsert nemesis=",
 :skew :small,
 :start-time
 #object[org.joda.time.DateTime 0x138a952f "2019-03-27T22:06:16.000Z"],
 :nemesis-interval 10,
 :net
 #object[jepsen.net$reify__5331 0x7d8d671b "jepsen.net$reify__5331@7d8d671b"],
 :client {:conn nil},
 :barrier
 #object[java.util.concurrent.CyclicBarrier 0x37cc6017 "java.util.concurrent.CyclicBarrier@37cc6017"],
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path nil},
 :retry-db-setup false,
 :tracing {:endpoint nil, :config true, :exporter nil},
 :local-binary "./dgraph",
 :checker
 #object[jepsen.checker$compose$reify__4889 0x59043741 "jepsen.checker$compose$reify__4889@59043741"],
 :defer-db-teardown false,
 :nemesis
 #object[jepsen.nemesis$compose$reify__5459 0x36857d32 "jepsen.nemesis$compose$reify__5459@36857d32"],
 :active-histories #<Atom@5e72c82a: #{}>,
 :nodes ["n1" "n2" "n3" "n4" "n5"],
 :test-count 1,
 :replicas 3,
 :force-download true,
 :total-amount 100,
 :generator
 (gen/timelimit 300 (gen/concat [(gen/on #{:nemesis} (gen/delayfn #object[clojure.core$partial$fn__5561 0x4ba1f425 "clojure.core$partial$fn__5561@4ba1f425"] (gen/gvoid))) (gen/on #object[clojure.core$complement$fn__5391 0x11577ab8 "clojure.core$complement$fn__5391@11577ab8"] (gen/mix [(gen/filter #object[jepsen.tests.bank$fn__1508 0x5759edff "jepsen.tests.bank$fn__1508@5759edff"] #object[jepsen.tests.bank$transfer 0x7d2be319 "jepsen.tests.bank$transfer@7d2be319"]) #object[jepsen.tests.bank$read 0x2dfd157b "jepsen.tests.bank$read@2dfd157b"]]))])),
 :max-transfer 5,
 :os
 #object[jepsen.os.debian.Debian 0x64381526 "jepsen.os.debian.Debian@64381526"],
 :time-limit 300,
 :version "v1.0.12-rc3-247-gf9ba33bd7",
 :upsert-schema true,
 :workload :bank,
 :accounts [0 1 2 3 4 5 6 7],
 :rebalance-interval "10h"}

INFO [2019-03-27 22:06:17,292] jepsen node n3 - jepsen.os.debian n3 setting up debian
INFO [2019-03-27 22:06:17,292] jepsen node n2 - jepsen.os.debian n2 setting up debian
INFO [2019-03-27 22:06:17,294] jepsen node n1 - jepsen.os.debian n1 setting up debian
INFO [2019-03-27 22:06:17,294] jepsen node n4 - jepsen.os.debian n4 setting up debian
INFO [2019-03-27 22:06:17,295] jepsen node n5 - jepsen.os.debian n5 setting up debian
INFO [2019-03-27 22:06:19,618] jepsen node n2 - jepsen.os.debian Installing #{libzip2}
INFO [2019-03-27 22:06:19,618] jepsen node n4 - jepsen.os.debian Installing #{libzip2}
INFO [2019-03-27 22:06:19,666] jepsen node n5 - jepsen.os.debian Installing #{libzip2}
INFO [2019-03-27 22:06:19,712] jepsen node n1 - jepsen.os.debian Installing #{libzip2}
INFO [2019-03-27 22:06:19,726] jepsen node n3 - jepsen.os.debian Installing #{libzip2}
WARN [2019-03-27 22:06:20,978] main - jepsen.core Test crashed!
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}} {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_191]
	at clojure.core$deref_future.invokeStatic(core.clj:2292) ~[clojure-1.9.0.jar:na]
	at clojure.core$future_call$reify__8097.deref(core.clj:6894) ~[clojure-1.9.0.jar:na]
	at clojure.core$deref.invokeStatic(core.clj:2312) ~[clojure-1.9.0.jar:na]
	at clojure.core$deref.invoke(core.clj:2298) ~[clojure-1.9.0.jar:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at jepsen.control$on_nodes.invokeStatic(control.clj:385) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invoke(control.clj:369) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invokeStatic(control.clj:374) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invoke(control.clj:369) ~[jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_$fn__5703.invoke(core.clj:549) ~[jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_.invokeStatic(core.clj:538) [jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_.invoke(core.clj:467) [jepsen-0.1.12.jar:na]
	at jepsen.cli$single_test_cmd$fn__6410.invoke(cli.clj:362) [jepsen-0.1.12.jar:na]
	at jepsen.cli$run_BANG_.invokeStatic(cli.clj:299) [jepsen-0.1.12.jar:na]
	at jepsen.cli$run_BANG_.invoke(cli.clj:229) [jepsen-0.1.12.jar:na]
	at jepsen.dgraph.core$_main.invokeStatic(core.clj:235) [na:na]
	at jepsen.dgraph.core$_main.doInvoke(core.clj:232) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:2422) [clojure-1.9.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:581) [clojure-1.9.0.jar:na]
	at user$eval149.invokeStatic(form-init5452604076854470541.clj:1) [na:na]
	at user$eval149.invoke(form-init5452604076854470541.clj:1) [na:na]
	at clojure.lang.Compiler.eval(Compiler.java:7062) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.eval(Compiler.java:7052) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.load(Compiler.java:7514) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.loadFile(Compiler.java:7452) [clojure-1.9.0.jar:na]
	at clojure.main$load_script.invokeStatic(main.clj:278) [clojure-1.9.0.jar:na]
	at clojure.main$init_opt.invokeStatic(main.clj:280) [clojure-1.9.0.jar:na]
	at clojure.main$init_opt.invoke(main.clj:280) [clojure-1.9.0.jar:na]
	at clojure.main$initialize.invokeStatic(main.clj:311) [clojure-1.9.0.jar:na]
	at clojure.main$null_opt.invokeStatic(main.clj:345) [clojure-1.9.0.jar:na]
	at clojure.main$null_opt.invoke(main.clj:342) [clojure-1.9.0.jar:na]
	at clojure.main$main.invokeStatic(main.clj:424) [clojure-1.9.0.jar:na]
	at clojure.main$main.doInvoke(main.clj:387) [clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.lang.Var.applyTo(Var.java:702) [clojure-1.9.0.jar:na]
	at clojure.main.main(main.java:37) [clojure-1.9.0.jar:na]
Caused by: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}}
	at slingshot.support$stack_trace.invoke(support.clj:201) ~[knossos-0.3.4.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:127) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:122) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.invokeStatic(control.clj:163) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.doInvoke(control.clj:160) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invoke(core.clj:652) ~[clojure-1.9.0.jar:na]
	at jepsen.control$exec.invokeStatic(control.clj:179) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec.doInvoke(control.clj:173) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.doInvoke(core.clj:652) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:660) [clojure-1.9.0.jar:na]
	at jepsen.os.debian$install.invokeStatic(debian.clj:98) ~[na:na]
	at jepsen.os.debian$install.invoke(debian.clj:78) ~[na:na]
	at jepsen.os.debian.Debian$fn__415.invoke(debian.clj:149) ~[na:na]
	at jepsen.os.debian.Debian.setup_BANG_(debian.clj:147) ~[na:na]
	at jepsen.os$fn__2294$G__2288__2298.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at jepsen.os$fn__2294$G__2287__2303.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at clojure.core$partial$fn__5561.invoke(core.clj:2617) ~[clojure-1.9.0.jar:na]
	at jepsen.control$on_nodes$fn__2893.invoke(control.clj:384) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:661) ~[clojure-1.9.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.9.0.jar:na]
	at jepsen.util$real_pmap$launcher__2044$fn__2045.invoke(util.clj:50) ~[jepsen-0.1.12.jar:na]
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.9.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
ERROR [2019-03-27 22:06:20,987] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}} {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_191]
	at clojure.core$deref_future.invokeStatic(core.clj:2292) ~[clojure-1.9.0.jar:na]
	at clojure.core$future_call$reify__8097.deref(core.clj:6894) ~[clojure-1.9.0.jar:na]
	at clojure.core$deref.invokeStatic(core.clj:2312) ~[clojure-1.9.0.jar:na]
	at clojure.core$deref.invoke(core.clj:2298) ~[clojure-1.9.0.jar:na]
	at clojure.core$map$fn__5587.invoke(core.clj:2745) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.9.0.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RT.seq(RT.java:528) ~[clojure-1.9.0.jar:na]
	at clojure.core$seq__5124.invokeStatic(core.clj:137) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75) ~[clojure-1.9.0.jar:na]
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13) ~[clojure-1.9.0.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6748) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invokeStatic(core.clj:6815) ~[clojure-1.9.0.jar:na]
	at clojure.core$into.invoke(core.clj:6807) ~[clojure-1.9.0.jar:na]
	at jepsen.control$on_nodes.invokeStatic(control.clj:385) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invoke(control.clj:369) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invokeStatic(control.clj:374) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$on_nodes.invoke(control.clj:369) ~[jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_$fn__5703.invoke(core.clj:549) ~[jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_.invokeStatic(core.clj:538) ~[jepsen-0.1.12.jar:na]
	at jepsen.core$run_BANG_.invoke(core.clj:467) ~[jepsen-0.1.12.jar:na]
	at jepsen.cli$single_test_cmd$fn__6410.invoke(cli.clj:362) ~[jepsen-0.1.12.jar:na]
	at jepsen.cli$run_BANG_.invokeStatic(cli.clj:299) [jepsen-0.1.12.jar:na]
	at jepsen.cli$run_BANG_.invoke(cli.clj:229) [jepsen-0.1.12.jar:na]
	at jepsen.dgraph.core$_main.invokeStatic(core.clj:235) [na:na]
	at jepsen.dgraph.core$_main.doInvoke(core.clj:232) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:2422) [clojure-1.9.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:581) [clojure-1.9.0.jar:na]
	at user$eval149.invokeStatic(form-init5452604076854470541.clj:1) [na:na]
	at user$eval149.invoke(form-init5452604076854470541.clj:1) [na:na]
	at clojure.lang.Compiler.eval(Compiler.java:7062) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.eval(Compiler.java:7052) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.load(Compiler.java:7514) [clojure-1.9.0.jar:na]
	at clojure.lang.Compiler.loadFile(Compiler.java:7452) [clojure-1.9.0.jar:na]
	at clojure.main$load_script.invokeStatic(main.clj:278) [clojure-1.9.0.jar:na]
	at clojure.main$init_opt.invokeStatic(main.clj:280) [clojure-1.9.0.jar:na]
	at clojure.main$init_opt.invoke(main.clj:280) [clojure-1.9.0.jar:na]
	at clojure.main$initialize.invokeStatic(main.clj:311) [clojure-1.9.0.jar:na]
	at clojure.main$null_opt.invokeStatic(main.clj:345) [clojure-1.9.0.jar:na]
	at clojure.main$null_opt.invoke(main.clj:342) [clojure-1.9.0.jar:na]
	at clojure.main$main.invokeStatic(main.clj:424) [clojure-1.9.0.jar:na]
	at clojure.main$main.doInvoke(main.clj:387) [clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.lang.Var.applyTo(Var.java:702) [clojure-1.9.0.jar:na]
	at clojure.main.main(main.java:37) [clojure-1.9.0.jar:na]
Caused by: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.control/nonzero-exit, :cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :exit 100, :out "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", :err "E: Unable to locate package libzip2\n", :host "n1", :action {:cmd "sudo -S -u root bash -c \"cd /; env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes libzip2\"", :in "root\n"}}
	at slingshot.support$stack_trace.invoke(support.clj:201) ~[knossos-0.3.4.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invokeStatic(control.clj:127) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$throw_on_nonzero_exit.invoke(control.clj:122) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.invokeStatic(control.clj:163) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec_STAR_.doInvoke(control.clj:160) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invoke(core.clj:652) ~[clojure-1.9.0.jar:na]
	at jepsen.control$exec.invokeStatic(control.clj:179) ~[jepsen-0.1.12.jar:na]
	at jepsen.control$exec.doInvoke(control.clj:173) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:665) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.doInvoke(core.clj:652) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:660) [clojure-1.9.0.jar:na]
	at jepsen.os.debian$install.invokeStatic(debian.clj:98) ~[na:na]
	at jepsen.os.debian$install.invoke(debian.clj:78) ~[na:na]
	at jepsen.os.debian.Debian$fn__415.invoke(debian.clj:149) ~[na:na]
	at jepsen.os.debian.Debian.setup_BANG_(debian.clj:147) ~[na:na]
	at jepsen.os$fn__2294$G__2288__2298.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at jepsen.os$fn__2294$G__2287__2303.invoke(os.clj:4) ~[jepsen-0.1.12.jar:na]
	at clojure.core$partial$fn__5561.invoke(core.clj:2617) ~[clojure-1.9.0.jar:na]
	at jepsen.control$on_nodes$fn__2893.invoke(control.clj:384) ~[jepsen-0.1.12.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:657) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) [clojure-1.9.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:661) ~[clojure-1.9.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995) ~[clojure-1.9.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.9.0.jar:na]
	at jepsen.util$real_pmap$launcher__2044$fn__2045.invoke(util.clj:50) ~[jepsen-0.1.12.jar:na]
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022) ~[clojure-1.9.0.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.9.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
```
